In [ ]:
!python --version

In [ ]:
import time
for i in range(10):
    time.sleep(1)
    print(i)

In [ ]:
a=1.5+0.5j

In [ ]:
a.real

In [ ]:
a.imag

In [ ]:
type(a)

In [ ]:
type(1+0j)

In [ ]:
7*3

In [ ]:
7*3.

In [ ]:
8%3

In [ ]:
colors = ['red', 'blue', 'green', 'black', 'white']

In [ ]:
colors.extend(['pink','purple'])

In [ ]:
colors.append(['one','two'])

In [ ]:
colors

In [ ]:
rcolors = colors[::-1]

In [ ]:
rcolors

In [ ]:
colors

In [ ]:
colors[::]

In [ ]:
colors[-1:0:-1]

In [ ]:
colors[2]=1

In [ ]:
colors

In [ ]:
colors.insert(2, "tristan")
colors

In [ ]:
type(colors)

In [ ]:
print('Hi, \t what''s \n up?')  #tab character and new line character

In [ ]:
def test(x,y):
    z=1
    d=x//y
    while d>y:
        d=d//y
        z+=1
    print(z)  

In [ ]:
test(20,5)

In [ ]:
list=[1]
def fibo(n):
        count=1
        x=0
        y=1
        while len(list)<=n-1:
            list.append(y)
            y=list[count]+list[count-1]
            count+=1
        print(list)

In [ ]:
fibo(3)

In [2]:
import numpy as np

In [ ]:
array

In [ ]:
def quicksrt(ls):
    lst = list()
    less = list()
    greater = list()
    if len(ls)< 2:
        return ls
    pv = ls[0]
    pv1 =list()
    pv1.append(pv)
    ls1=ls[1:]
    for i in ls1:
        if i < pv + 1:
            less.append(i)
        else: 
            greater.append(i)
    return quicksrt(less)+pv1+quicksrt(greater)

In [ ]:
array =np.random.randint(1,100,50)

In [ ]:
def quickstart(array):
    l=array[0]
    p=array[-1]
    r=array[-2]
    while l<p:
        l=
    
    
    

In [ ]:
np.zeros(5)

In [ ]:
np.ones((2,3,4),dtype=np.int16)

In [ ]:
print(np.arange(10,20,5))

In [ ]:
np.linspace(0,2,9)

In [ ]:
np.eye(2)

In [ ]:
np.save('try_array',array)

In [3]:
np.empty((3,2))

array([[ 2.68156159e+154, -3.11109945e+231],
       [ 1.48219694e-323,              nan],
       [ 0.00000000e+000,  4.17201348e-309]])

In [5]:
a=np.random.randint(1,1000,10)
b=np.ones(10)*3

In [9]:
a*b

array([2394., 1821., 2571., 1353., 1191., 2262.,  990.,  873., 1800.,
       2559.])

In [10]:
a-3

array([795, 604, 854, 448, 394, 751, 327, 288, 597, 850])